version: '3.3'

services:
  auth-api:
    env_file:
      - ./auth/.env
    build:
      context: ./auth
      dockerfile: Dockerfile
    # volumes:
    #   - ./db_data:/app/db_data
    restart: always
    ports:
      - "8080:8080"
  fetch-api:
    env_file:
      - ./fetch/.env
    build:
      context: ./fetch
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"